Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -126,4 +126,11 @@ jobs:
         uses: hashicorp/setup-terraform@v1
 
       - name: Terraform Apply
-        run: terraform apply -auto-approve
+        run: |
+          set +e  # This allows the script to continue even after errors
+          terraform apply -auto-approve > apply_output.txt
+          if grep -q "Error:" apply_output.txt; then
+            echo "Terraform apply failed. Check the logs for details."
+            exit 1
+          fi
+
